# This file will contain the endpoints for creating, reading, updating, and deleting transactions.

from fastapi import HTTPException
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from app.api.dependencies import get_current_user
from app.api.dependencies import get_db
from app.schemas.user import UserRead
from app.schemas.transaction import TransactionCreate, TransactionRead
from app.db.models.transaction import UserTransaction
from app.db.models.financial_report import FinancialReport

router = APIRouter()

# create new transaction; the router will be mounted under `/transactions` in the main router
@router.post("", response_model=TransactionRead)
def create_transaction(transaction: TransactionCreate, db: Session = Depends(get_db), current_user: UserRead = Depends(get_current_user)):
    
    # error handling report_id needs to be valid and belong to the current user; you would normally check this against the database
    report = db.query(FinancialReport).filter(
        FinancialReport.id == transaction.report_id,
        FinancialReport.user_id == current_user.id
    ).first()

    if not report:
        raise HTTPException(
            status_code=404,
            detail="Report not found or does not belong to the user"
        )
    
    
    
    # when wiring up a real database you'd normally let the database generate the id
    # and look up the report by its id or name; here we accept the report_id from the client
    db_transaction = UserTransaction(
        # id is auto-generated by the database, so we don't set it manually here
        user_id=current_user.id,
        report_id=transaction.report_id,
        amount=transaction.amount,
        category=transaction.category,
        description=transaction.description,
        date=transaction.date
    )
    
    db.add(db_transaction)
    db.commit()
    db.refresh(db_transaction)
    
    return db_transaction