# This file will contain the endpoints for creating, reading, updating, and deleting transactions.

from fastapi import HTTPException
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from app.api.dependencies import get_current_user
from app.api.dependencies import get_db
from app.schemas.user import UserRead
from app.schemas.transaction import TransactionCreate, TransactionRead
from app.db.models.transaction import UserTransaction
from app.db.models.financial_report import FinancialReport
from app.crud.transaction import get_transaction_filter

router = APIRouter()

# create new transaction; the router will be mounted under `/transactions` in the main router
@router.post("", response_model=TransactionRead)
def create_transaction(transaction: TransactionCreate, db: Session = Depends(get_db), current_user: UserRead = Depends(get_current_user)):
    
    # error handling report_id needs to be valid and belong to the current user; you would normally check this against the database
    report = db.query(FinancialReport).filter(
        FinancialReport.id == transaction.report_id,
        FinancialReport.user_id == current_user.id
    ).first()

    if not report:
        raise HTTPException(
            status_code=404,
            detail="Report not found or does not belong to the user"
        )
    
    # when wiring up a real database you'd normally let the database generate the id
    # and look up the report by its id or name; here we accept the report_id from the client
    db_transaction = UserTransaction(
        # id is auto-generated by the database, so we don't set it manually here
        user_id=current_user.id,
        report_id=transaction.report_id,
        amount=transaction.amount,
        category=transaction.category,
        description=transaction.description,
        date=transaction.date
    )
    
    db.add(db_transaction)
    db.commit()
    db.refresh(db_transaction)
    
    return db_transaction

@router.get("/", response_model=list[TransactionRead])
def filter_transactions(
    skip: int = 0,
    limit: int = 100,
    start_date: str = None,
    end_date: str = None,
    min_amount: float = None,
    max_amount: float = None,
    report_id: int = None,
    category: str = None,
    search: str = None,
    db: Session = Depends(get_db),
    current_user: UserRead = Depends(get_current_user)
):
    return get_transaction_filter(
        db=db,
        user_id=current_user.id,
        skip=skip,
        limit=limit,
        start_date=start_date,
        end_date=end_date,
        min_amount=min_amount,
        max_amount=max_amount,
        report_id=report_id,
        category=category,
        search=search
    )