from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from app.api.dependencies import get_current_user
from app.schemas.financial_report import FinancialReportCreate, FinancialReportRead
from app.db.models.financial_report import FinancialReport
from datetime import datetime
from app.api.dependencies import get_db
from app.schemas.user import UserRead

router = APIRouter()

@router.post("/report", response_model=FinancialReportRead)
def create_financial_report(report: FinancialReportCreate, db: Session = Depends(get_db), current_user: UserRead = Depends(get_current_user)):
    db_report = FinancialReport(
        # id is auto-generated by the database, so we don't set it manually here
        user_id=current_user.id,
        report_name=report.report_name,
        description=report.description,
        created_at=datetime.now()
    )
    
    db.add(db_report)
    db.commit()
    db.refresh(db_report)
    
    return db_report